### ISSUE TITLE
Las esperas deberian ser dinamicas

### ISSUE THREAD

**Issue by FabrizioOtranto** [derodriguezc/daniel-rodriguez#1]
Nunca es buena idea usar cy.wait.

La mejor idea seria encontrar el selector del circulo de carga y esperar que no existan con un timeout (clase-5)

https://github.com/derodriguezc/daniel-rodriguez/blob/e72a03a16ca90a89d079ab1f181c8178a2174bc1/cypress/support/pages/ReciptPage.js#L9

**Comment by derodriguezc** [comment]
Resuelto

**Comment by derodriguezc** [comment]
Resuelto
