### ISSUE TITLE
Pertenece a shoppingCartPage

### ISSUE THREAD

**Issue by FabrizioOtranto** [derodriguezc/daniel-rodriguez#2]
El metodo para ir a la pagina de checkout pertenece a la pagina shoppingCartPage

https://github.com/derodriguezc/daniel-rodriguez/blob/e72a03a16ca90a89d079ab1f181c8178a2174bc1/cypress/support/pages/CheckOutPage.js#L11

**Comment by derodriguezc** [comment]
Resuelto
