### ISSUE TITLE
Falto agregar la asersion

### ISSUE THREAD

**Issue by FabrizioOtranto** [derodriguezc/daniel-rodriguez#3]
Deberias utilizar una asersion para verificar que el elemento contiene el nombre y apellido. En vez de usar have.text podrias usar includes

https://github.com/derodriguezc/daniel-rodriguez/blob/e72a03a16ca90a89d079ab1f181c8178a2174bc1/cypress/support/pages/ReciptPage.js#L12

**Comment by derodriguezc** [comment]
Resuelto
