### ISSUE TITLE
Falto asersion

### ISSUE THREAD

**Issue by FabrizioOtranto** [derodriguezc/daniel-rodriguez#4]
Deberias utilizar una asersion para verificar que el elemento contiene precio. En vez de usar have.text podrias usar includes de ser necesario

https://github.com/derodriguezc/daniel-rodriguez/blob/e72a03a16ca90a89d079ab1f181c8178a2174bc1/cypress/support/pages/ReciptPage.js#L24

**Comment by derodriguezc** [comment]
Resuelto
